# Generated by Django 3.2.25 on 2025-05-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymclass',
            name='available_time_slots',
        ),
    ]
