# Generated by Django 3.2.25 on 2025-05-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_gymclass_available_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='available_time_slots',
            field=models.CharField(default='10:00,12:00,14:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class_images/'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.gymclass')),
            ],
        ),
    ]
