# Generated by Django 5.2.1 on 2025-05-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20250520_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
